### ISSUE TITLE
Rollenbilder ausfeilen

### ISSUE THREAD

**Issue by miafy** [ink-inc/MagicMittelalterStory#29]
Geschlechter, Alter, Magie-Arten, Rassen, Religion...
Konflikte dürfen sein

**Comment by Medsmiley** [comment]
festlegen und beschreiben, wie sich was warum entwickelt hat. Muss nicht dem damaligen unserer Vergangenheit gleichen, aber sollte tw. sinnvoll (was zB die Körperkraft betrifft) und tw. genauso bescheuert (was irgendwelche Zuordnungen aufgrund von religiösen Dingen oder Unwissenheit die Körper/den Geist/etc betreffend angeht) sein
